//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Orkidea.ApogeoWinservice.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class SAP_DETALLE_ASIENTO
    {
        public long ID_DETALLE_ASIENTO { get; set; }
        public string JdtNum { get; set; }
        public Nullable<long> LineNum { get; set; }
        public string Account { get; set; }
        public Nullable<decimal> Debit { get; set; }
        public Nullable<decimal> Credit { get; set; }
        public Nullable<System.DateTime> DueDate { get; set; }
        public string LineMemo { get; set; }
        public Nullable<System.DateTime> RefDate { get; set; }
        public string Ref1 { get; set; }
        public string Ref2 { get; set; }
        public string Ref3Line { get; set; }
        public string Project { get; set; }
        public Nullable<System.DateTime> TaxDate { get; set; }
        public string ProfitCode { get; set; }
        public string OcrCode2 { get; set; }
        public string OcrCode3 { get; set; }
        public string U_InfoCo01 { get; set; }
        public string ESTADO { get; set; }
        public Nullable<int> TransId { get; set; }
    }
}
