//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Orkidea.ApogeoWinservice.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class SAP_SOCIOS_NEGOCIO
    {
        public long ID_SOCIO_NEGOCIO { get; set; }
        public Nullable<long> RecordKey { get; set; }
        public string CardCode { get; set; }
        public string DebitorAccount { get; set; }
        public string Territory { get; set; }
        public string AccrualCriteria { get; set; }
        public string BlockDunning { get; set; }
        public string CardForeignName { get; set; }
        public string CardName { get; set; }
        public string CardType { get; set; }
        public string Cellular { get; set; }
        public string CollectionAuthorization { get; set; }
        public string CreditLimit { get; set; }
        public string Currency { get; set; }
        public string DeductibleAtSource { get; set; }
        public string DeferredTax { get; set; }
        public string EmailAddress { get; set; }
        public string Equalization { get; set; }
        public string Fax { get; set; }
        public string FederalTaxID { get; set; }
        public string FreeText2 { get; set; }
        public string GroupCode { get; set; }
        public string PartialDelivery { get; set; }
        public string PayTermsGrpCode { get; set; }
        public string Phone1 { get; set; }
        public string Phone2 { get; set; }
        public string Properties1 { get; set; }
        public string Properties2 { get; set; }
        public string Properties3 { get; set; }
        public string SalesPersonCode { get; set; }
        public string Pager { get; set; }
        public string VatLiable { get; set; }
        public string B1 { get; set; }
        public string VatGroup { get; set; }
        public string Website { get; set; }
        public string DunningTerm { get; set; }
        public string Priority { get; set; }
        public string PriceListNum { get; set; }
        public string PeymentMethodCode { get; set; }
        public string WTCode { get; set; }
        public string SubjectToWithholdingTax { get; set; }
        public string U_BPCO_City { get; set; }
        public string U_BPCO_CS { get; set; }
        public string U_BPCO_Nombre { get; set; }
        public string U_BPCO_1Apellido { get; set; }
        public string U_BPCO_2Apellido { get; set; }
        public string U_BPCO_BPExt { get; set; }
        public string U_BPCO_TP { get; set; }
        public string U_BPCO_RTC { get; set; }
        public string U_BPCO_TDC { get; set; }
        public string U_BPCO_Address { get; set; }
        public string DownPaymentInterimAccount { get; set; }
        public string ESTADO { get; set; }
    }
}
