//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Orkidea.ApogeoWinservice.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class SAP_CABEZA_ASIENTO
    {
        public long ID_CABEZA_ASIENTO { get; set; }
        public string JdtNum { get; set; }
        public Nullable<System.DateTime> RefDate { get; set; }
        public string Memo { get; set; }
        public string Ref1 { get; set; }
        public string Ref2 { get; set; }
        public string TransCode { get; set; }
        public string Project { get; set; }
        public Nullable<System.DateTime> TaxDate { get; set; }
        public Nullable<System.DateTime> VatDate { get; set; }
        public string StampTax { get; set; }
        public string AutoVAT { get; set; }
        public string ESTADO { get; set; }
        public Nullable<int> TransId { get; set; }
    }
}
