//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IntegracionApogeo.DataAccessEF
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using IntegracionApogeo.Business.Entities;
    
    public partial class SAP_TEMP_APOGEOEntities : DbContext
    {
        public SAP_TEMP_APOGEOEntities()
            : base("name=SAP_TEMP_APOGEOEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<SAP_CABEZA_ASIENTO> SAP_CABEZA_ASIENTO { get; set; }
        public virtual DbSet<SAP_DETALLE_ASIENTO> SAP_DETALLE_ASIENTO { get; set; }
        public virtual DbSet<SAP_SOCIOS_NEGOCIO> SAP_SOCIOS_NEGOCIO { get; set; }
    }
}
